version: "2.3"
services: 
  pytorch-train:
    container_name: pytorch-train
    image: aisl/pytorch:latest
    runtime: nvidia
    build: .
    command: >
      python /root/PyTorch-ENet/main.py -m train 
      --save-dir /root/PyTorch-ENet/save/ENet_CamVid_matsuzaki_20190921/ 
      --name my_cityscapes_20190921 
      --dataset camvid 
      --dataset-dir /tmp/dataset/CamVid/ 
      --batch-size 8
    volumes:
      - ./PyTorch-ENet:/root/PyTorch-ENet
      - /media/data/dataset/matsuzaki:/tmp/dataset
    shm_size: 1G

  tensorboard:
    container_name: tensorboard
    image: aisl/pytorch:latest
    command: tensorboard --logdir /root/PyTorch-ENet/runs
    build: .
    ports:
      - 60006:6006
    volumes:
      - ./PyTorch-ENet:/root/PyTorch-ENet

  master:
    container_name: pytorch-ros-master
    image: ros:kinetic-ros-core
    command: roscore
    environment:
      - ROS_MASTER_URI=http://localhost:11311
    tty: true

  pytorch-ros:
    container_name: pytorch-ros-node
    depends_on:
      - master
    build: .
    runtime: nvidia
    image: aisl/pytorch:latest
    command: roslaunch pytorch_enet_ros pytorch_enet_ros.launch
    environment:
      - ROS_MASTER_URI=http://pytorch-ros-master:11311
      - ROS_IP=172.24.0.3
    volumes:
      - ./catkin_ws/:/root/catkin_ws/
      - ./PyTorch-ENet:/root/PyTorch-ENet
      - /media/data/dataset/matsuzaki:/tmp/dataset
    tty: true
    shm_size: 1G

  catkin-build:
    container_name: catkin-build
    depends_on:
      - master
    build: .
    runtime: nvidia
    image: aisl/pytorch:latest
    command: bash -c "cd /root/catkin_ws && catkin build"
    environment:
      - ROS_MASTER_URI=http://pytorch-ros-master:11311
    volumes:
      - ./catkin_ws/:/root/catkin_ws/
      - ./PyTorch-ENet:/root/PyTorch-ENet
      - /media/data/dataset/matsuzaki:/tmp/dataset
    tty: true
    shm_size: 1G

  rviz:
    container_name: pytorch-ros-rviz
    depends_on:
      - master
    image: osrf/ros:kinetic-desktop-full
    command: rviz
    environment:
      - ROS_MASTER_URI=http://pytorch-ros-master:11311
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    tty: true
