version: "2.3"
services:
  master:
    container_name: pytorch-ros-master
    image: ros:noetic
    command: roscore
    environment:
      - ROS_MASTER_URI=http://localhost:11311
    tty: true

  pytorch-ros:
    container_name: pytorch-ros-node
    depends_on:
      - master
    build: .
    runtime: nvidia
    image: aisl/pytorch-enet:torch1.13.0-noetic
    command: roslaunch pytorch_ros pytorch_enet_ros.launch image:=/kinect2/qhd/image_color_rect
    environment:
      - ROS_MASTER_URI=http://pytorch-ros-master:11311
    volumes:
      - ./catkin_ws/:/root/catkin_ws/
      - /media/data/dataset/matsuzaki:/tmp/dataset
    tty: true
    shm_size: 1G

  pytorch-online-ros:
    container_name: pytorch-ros-online-node
    depends_on:
      - master
    build: .
    runtime: nvidia
    image: aisl/pytorch-enet:torch1.13.0-noetic
    command: bash -c "nvidia-smi && rosrun pytorch_ros pytorch_enet_ros_node.py ~image:=/kinect2/qhd/image_color_rect"
    environment:
      - ROS_MASTER_URI=http://pytorch-ros-master:11311
      - PYTHONPATH=${PYTHONPATH}:/root/catkin_ws/src/pytorch_enet_ros/espdnet/
    volumes:
      - ./catkin_ws/:/root/catkin_ws/
    stdin_open: true
    tty: true
    shm_size: 5G

  catkin-build:
    container_name: catkin-build
    build: .
    runtime: nvidia
    image: aisl/pytorch-enet:torch1.13.0-noetic
    # command: bash -c "ls /opt/ros/ && source /opt/ros/melodic/setup.bash && cd /root/catkin_ws && catkin build -DCMAKE_BUILD_TYPE=Debug"
    working_dir: "/root/catkin_ws/"
    command: bash -c "source /opt/ros/noetic/setup.sh && catkin build -DCMAKE_BUILD_TYPE=Debug"
    environment:
      - CMAKE_PREFIX_PATH=/opt/ros/noetic:${CMAKE_PREFIX_PATH}
    volumes:
      - ./catkin_ws/:/root/catkin_ws/ #  - /media/data/dataset/matsuzaki:/tmp/dataset
    tty: true
    shm_size: 1G

  bash:
    container_name: bash
    build: .
    runtime: nvidia
    image: aisl/pytorch-enet:torch1.13.0-noetic
    command: bash
    environment:
      - ROS_MASTER_URI=http://pytorch-ros-master:11311
      - PYTHONPATH=${PYTHONPATH}:/root/catkin_ws/src/pytorch_enet_ros/espdnet/
    volumes:
      - ./catkin_ws/:/root/catkin_ws/
    stdin_open: true
    tty: true
    shm_size: 5G
