version: "2.3"
services: 
  pytorch-train:
    container_name: pytorch-train
    image: aisl/pytorch-enet:20.03-py3
    runtime: nvidia
    build: .
    command: >
      python /root/PyTorch-ENet/main.py -m train 
      --save-dir /root/PyTorch-ENet/save/ENet_CamVid_matsuzaki_20190921/ 
      --name my_cityscapes_20190921 
      --dataset camvid 
      --dataset-dir /tmp/dataset/CamVid/ 
      --batch-size 8
    volumes:
      - ./PyTorch-ENet:/root/PyTorch-ENet
      - /media/data/dataset/matsuzaki:/tmp/dataset
    shm_size: 1G

  tensorboard:
    container_name: tensorboard
    image: aisl/pytorch-enet:latest
    command: tensorboard --logdir /root/PyTorch-ENet/runs
    build: .
    ports:
      - 60006:6006
    volumes:
      - ./PyTorch-ENet:/root/PyTorch-ENet

  master:
    container_name: master
    image: ros:kinetic-ros-core
    command: roscore
    environment:
      - ROS_MASTER_URI=http://localhost:11311
    tty: true

  pytorch-ros:
    container_name: pytorch-ros-node
    depends_on:
      - master
    build: .
    runtime: nvidia
    image: aisl/pytorch-enet:20.03-py3
    command: roslaunch pytorch_enet_ros pytorch_enet_ros.launch image:=/kinect2/qhd/image_color_rect
    environment:
      - ROS_MASTER_URI=http://master:11311
        #      - ROS_IP=172.24.0.3
    volumes:
      - ./catkin_ws/:/root/catkin_ws/
      - ./PyTorch-ENet:/root/PyTorch-ENet
      - /media/data/dataset/matsuzaki:/tmp/dataset
    tty: true
    shm_size: 1G

  catkin-build:
    container_name: catkin-build
    build: .
    runtime: nvidia
    image: aisl/pytorch-enet:20.03-py3
    command: bash -c "source /opt/ros/melodic/setup.bash && cd /root/catkin_ws && catkin build -DCMAKE_BUILD_TYPE=Debug"
    environment:
      - CMAKE_PREFIX_PATH=/opt/ros/melodic:${CMAKE_PREFIX_PATH}
    volumes:
      - ./catkin_ws/:/root/catkin_ws/
      - ./PyTorch-ENet:/root/PyTorch-ENet
        #  - /media/data/dataset/matsuzaki:/tmp/dataset
    tty: true
    shm_size: 1G
